### ISSUE TITLE
Error on fresh install with next 12.0.10

### ISSUE THREAD

**Issue by MatteoGauthier** [preactjs/next-plugin-preact#55]
Got an error with next after fresh install of the plugin

```

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: 6.28.0
    Relevant packages:
      next: 12.0.10
      react: N/A
      react-dom: N/A

```

```
➜  archiver git:(main) ✗ yarn dev
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Cannot find module 'scheduler/package.json'
Require stack:
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/hot-reloader.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/next.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/lib/start-server.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/cli/next-dev.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._resolveFilename (/Users/matteogauthier/dev/archiver/node_modules/module-alias/index.js:49:29)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js:548:41)
    at Object.getBaseWebpackConfig [as default] (/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js:566:9)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/Users/matteogauthier/dev/archiver/node_modules/next/dist/trace/trace.js:75:20)
    at async Span.traceAsyncFn (/Users/matteogauthier/dev/archiver/node_modules/next/dist/trace/trace.js:75:20)
    at async HotReloader.start (/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/hot-reloader.js:329:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/hot-reloader.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/next-dev-server.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/next.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/lib/start-server.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/cli/next-dev.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  archiver git:(main) ✗ yarn dev > error
Error: Cannot find module 'scheduler/package.json'
Require stack:
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/hot-reloader.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/next.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/server/lib/start-server.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/cli/next-dev.js
- /Users/matteogauthier/dev/archiver/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._resolveFilename (/Users/matteogauthier/dev/archiver/node_modules/module-alias/index.js:49:29)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js:548:41)
    at Object.getBaseWebpackConfig [as default] (/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js:566:9)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/Users/matteogauthier/dev/archiver/node_modules/next/dist/trace/trace.js:75:20)
    at async Span.traceAsyncFn (/Users/matteogauthier/dev/archiver/node_modules/next/dist/trace/trace.js:75:20)
    at async HotReloader.start (/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/hot-reloader.js:329:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/build/webpack-config.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/hot-reloader.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/dev/next-dev-server.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/next.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/server/lib/start-server.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/cli/next-dev.js',
    '/Users/matteogauthier/dev/archiver/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
```

**Comment by neeraj3029** [comment]
This issue has been fixed with PR: https://github.com/vercel/next.js/pull/31264
You'll find it in the next release

**Comment by socramm9** [comment]
I get a diferent error on a fresh install. Ist it related?
![Bildschirmfoto 2022-02-20 um 14 52 03](https://user-images.githubusercontent.com/52098754/154846872-a14c263c-14d5-4167-91ba-30fdd0a3327f.png)

**Comment by Tobeyforce** [comment]
> This issue has been fixed with PR: [vercel/next.js#31264](https://github.com/vercel/next.js/pull/31264) You'll find it in the next release

When can we expect the next release, and what versions will be supported? :) Would be great to know!

**Comment by neeraj3029** [comment]
@Tobeyforce this should be in the latest release.
